
  CREATE TABLE "CGSYSADM"."FEES_TEST" 
   (	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SEQNO" NUMBER(*,0) NOT NULL ENABLE, 
	"FEE_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"AMOUNT" FLOAT(126), 
	"REMARK" VARCHAR2(2000 BYTE), 
	"GLCODE" VARCHAR2(30 BYTE), 
	"ENTDATE" DATE, 
	"PERIOD" NUMBER(*,0), 
	"USERNAME" VARCHAR2(16 BYTE) DEFAULT USER, 
	"VALID_FROM" DATE, 
	"JOBCOST" NUMBER(*,0), 
	"BILL_FMT" VARCHAR2(30 BYTE), 
	"SERVCAT_CODE" VARCHAR2(10 BYTE), 
	"SERV_CODE" VARCHAR2(10 BYTE), 
	"SERV_TYPE" VARCHAR2(3 BYTE), 
	"CO_ID" NUMBER(*,0), 
	"AMOUNT_GROSS" FLOAT(126), 
	"CURRENCY" NUMBER(*,0), 
	"GLCODE_DISC" VARCHAR2(30 BYTE), 
	"JOBCOST_ID_DISC" NUMBER(*,0), 
	"GLCODE_MINCOM" VARCHAR2(30 BYTE), 
	"JOBCOST_ID_MINCOM" NUMBER(*,0), 
	"REC_VERSION" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"CDR_ID" NUMBER(*,0), 
	"CDR_SUB_ID" NUMBER(*,0), 
	"UDR_BASEPART_ID" NUMBER(*,0), 
	"UDR_CHARGEPART_ID" NUMBER(*,0), 
	"TMCODE" NUMBER(*,0), 
	"VSCODE" NUMBER(*,0), 
	"SPCODE" NUMBER(*,0), 
	"SNCODE" NUMBER(*,0), 
	"EVCODE" NUMBER(*,0), 
	"FEE_CLASS" NUMBER(*,0) NOT NULL ENABLE, 
	"FU_PACK_ID" NUMBER(*,0), 
	"FUP_VERSION" NUMBER(*,0), 
	"FUP_SEQ" NUMBER(*,0), 
	"VERSION" NUMBER(*,0), 
	"FREE_UNITS_NUMBER" FLOAT(126), 
	"BILLING_ACCOUNT_ID" NUMBER(*,0), 
	"RELATIVE" CHAR(1 BYTE), 
	"OHXACT" NUMBER(*,0), 
	"PROMOTION_AND_TAX_FLAG" VARCHAR2(1 BYTE), 
	"DELETED" VARCHAR2(1 BYTE) DEFAULT ('N') NOT NULL ENABLE, 
	"DELETED_BY" VARCHAR2(16 BYTE), 
	"ORIG_PERIOD" NUMBER(*,0), 
	"DEACTIVATION_DATE" DATE, 
	"OHXACT_STONOGA" NUMBER(*,0)
   )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE INDEX "CGSYSADM"."FKIFEES_CO_IDCG_T" ON "CGSYSADM"."FEES_TEST" ("CO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_IDX" ;

  CREATE INDEX "CGSYSADM"."FKIFE_SERVSCG_T" ON "CGSYSADM"."FEES_TEST" ("SERVCAT_CODE", "SERV_CODE", "SERV_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_IDX" ;

  CREATE INDEX "CGSYSADM"."FKIFE_USNMCG_T" ON "CGSYSADM"."FEES_TEST" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_IDX" ;

  CREATE INDEX "CGSYSADM"."IX_FEES_BILACTCG_T" ON "CGSYSADM"."FEES_TEST" ("BILLING_ACCOUNT_ID", "PERIOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_IDX" ;

 CREATE SYNONYM CGSYSADM.FEES FOR "CGSYSADM"."FEES_TEST";
