ALTER TABLE FEES_TEST ADD CONSTRAINT "XXX" PRIMARY KEY ("CUSTOMER_ID", "SEQNO");

ALTER TABLE FEES_OHXACT_TEST ADD CONSTRAINT "FK_FEESOHXACT_FEES_TEST" FOREIGN KEY ("CUSTOMER_ID", "SEQNO") REFERENCES "CGSYSADM"."FEES_TEST" ("CUSTOMER_ID", "SEQNO") ENABLE;

