DROP TABLE "CGSYSADM"."FEES_OHXACT_DEL";

CREATE TABLE "CGSYSADM"."FEES_OHXACT_DEL" 
   (	"CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SEQNO" NUMBER(*,0) NOT NULL ENABLE, 
	"OHXACT" NUMBER(*,0), 
	"AMOUNT" FLOAT(126), 
	"PERIOD" NUMBER(*,0), 
	"BILL_DATE" DATE, 
	"USERNAME" VARCHAR2(16 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

